[package]
name = "palkia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
downcast = "0.11.0"

[dev-dependencies]
crossterm = "0.24.0"
aglet = { path = "../aglet" }
fastrand = "1.7.0"
